# -*- coding: utf-8 -*-
"""追加 finals_alg_ana.md 的 §6-§8。BT 代表反引号。"""
import os
ROOT = r'.'
OUT = os.path.join(ROOT, 'reports', 'finals_alg_ana.md')
L = []
def o(s=''): L.append(s)

o()
o('---')
o()
o('## 6. 代表题（8 道完整题面 + 解题思路）')
o()
o('> 题面按抽取原文转录，只做了最小必要的排版 LaTeX 化（如 x2+y2 写成 x²+y²、p−2 写成 p−2），')
o('> 题号、条件、结构均未改动；凡抽取有损处均在该题末尾标注。')
o()

o('### R1 · 2014 · 代数与数论 · Individual · Problem 3（三次域与 F_p 上的点数）')
o()
o('出处：BT./corpus/finals/2012_2025Algebra_Number_Theory_and_Combinatorics_Individual_2014_Algebra_Individual.txtBT（文字层完好）')
o()
o('> Problem 3. Let p > 3 be a prime. Consider the equation')
o('>')
o('> $$x^3 + y^3 = 1 \\quad (\\ast)$$')
o('>')
o('> in Z/pZ.')
o('> (1) When p ≡ 2 (3), find the number of solutions.')
o('> (2) When p ≡ 1 (3), prove that there exists a pair (a, b) of integers such that')
o('>   (a) 4p = a² + 27b²,')
o('>   (b) a ≡ 1 mod 3. (Note: a is unique.)')
o('> (3) (Continuation of (2)) When p ≡ 1 (3). Prove that (*) has p−2+a solution in Z/pZ.')
o()
o('**解题思路**')
o('1. 把问题看成有限域上仿射三次曲线的点数：N = #{(x,y) ∈ F_p² : x³+y³=1}。')
o('2. (1) p ≡ 2 (mod 3) 时 gcd(3, p−1) = 1，故 x ↦ x³ 是 F_p 上的置换。')
o('   于是对每个 y 恰有一个 x，解数直接是 p（含 y 任意取遍 F_p 的 p 个选择）——用「置换」代替枚举即可。')
o('3. (2) 是经典 Gauss 结果：p ≡ 1 (mod 3) 时 p 在 Q(ζ_3) = Q(√−3) 中分裂，p = ππ̄；')
o('   令 π = (a + b√−27)/2 即得 4p = a² + 27b²；再对 π 乘上 ζ_3 的幂使 a ≡ 1 (mod 3)，唯一性由单位的选择固定。')
o('4. (3) 是关键一步：用三次特征标 χ（F_p^× → μ_3）把点数的偏差写成 Jacobi 和。')
o('   对 t ≠ 0 记 N(t) = #{x³+y³ = t}，则 N(t) = p − 1 + χ(...) 形式；把 t = 1 代回并整理出 N = p − 2 + a，')
o('   其中 a 正好是 π + π̄（即 4p = a²+27b² 中那个 ≡1 mod 3 的 a）。')
o('   **不必真的算出 (a,b)**：题目只要求把解数用 (2) 中的 a 表示。')
o('5. 这道题是「数域分裂 × 特征标和 × 有限域点数」三件事的标准缝合，属总决赛压轴级（自评 5）。')
o()

o('### R2 · 2021 · 代数与数论 · Individual · Problem 1（局部域范数群）★ 原卷附官方解答')
o()
o('出处：BT./corpus/finals/2012_2025Algebra_Number_Theory_and_Combinatorics_Individual_2021_Algebra_Individual_S.txtBT')
o('（文件名带 BT(S)BT = 含官方解答；本题是本报告范围内**唯一能看到出题方解答**的题之一，另有 2021 ALG Overall 两题）')
o()
o('> Problem 1. (Individual round.) Let p be a prime number and Q_p the field of p-adic numbers.')
o('> Let n ≥ 1 be an integer and L = Q_p(ζ_{p^n}), where ζ_{p^n} denotes a primitive p^n-th roots of unity.')
o('> Determine the image of the norm map N_{L/Q_p} : L^× → Q_p^×.')
o('> You may use the inequality [L : Q_p] ≤ (Q_p^× : N_{L/Q_p}(L^×)) without proof in the case n ≥ 2.')
o()
o('**官方解答要点（原文抽取，已压缩）**')
o('> We will show that N_{L/Q_p}(L^×) = p^Z (1 + p^n Z_p).')
o('> Let Φ(X) = (X^{p^n} − 1)/(X^{p^{n−1}} − 1). Then Φ(X+1) is an Eisenstein polynomial. Thus Φ(X) is the minimal')
o('> polynomial of ζ_{p^n}, so that N_{L/Q_p}(1 − ζ_{p^n}) = Φ(1) = p.')
o('> We have [L : Q_p] = φ(p^n) = p^n − p^{n−1}. For p odd, the φ(p^n)-th power map on 1 + pZ_p is the composition')
o('> 1 + pZ_p −log→ pZ_p −φ(p^n)→ p^n Z_p −exp→ 1 + p^n Z_p. Thus N(1 + pZ_p) = 1 + p^n Z_p.')
o('> For p = 2 (n ≥ 2) 同理在 1 + 4Z_2 上得 N(1 + 4Z_2) = 1 + 2^{n+1}Z_2，并利用')
o('> 1 + 2^n Z_2 = (1 + 2^{n+1}Z_2) ⊔ 5^{2^{n−2}}(1 + 2^{n+1}Z_2) 与 5^{2^{n−2}} = N(2 + ζ_4)。')
o('> 反向包含：O_L 的剩余域是 F_p，故 N 在 O_L^× 上与 F_p^× 的 φ(p^n) 次幂映射相容，')
o('> 得 N(L^×) ∩ Z_p^× ⊆ 1 + pZ_p；n ≥ 2 时用题给不等式卡指数即可。')
o()
o('**解题思路**')
o('1. 先猜答案：范数群应该是「p 的整数次幂 × 主单位群 1 + p^nZ_p」——两个因子分别对应分歧与剩余域。')
o('2. 下界：用 1 − ζ_{p^n} 造出 p（Eisenstein 判别法给出极小多项式），再用 log/exp 把乘法群同构到加法群，')
o('   在加法群上 φ(p^n) 次幂映射就是乘 φ(p^n)，于是 1 + pZ_p 被映到 1 + p^n Z_p。')
o('3. 上界：范数在剩余域上诱导 φ(p^n) 次幂映射，F_p^× 的 φ(p^n) 次幂全为 1，故单位范数只能落在 1 + pZ_p。')
o('4. 最后用题给指数不等式（局部类域论的 [L:Q_p] ≤ 范数指数）夹逼，指数恰好对上。')
o('5. 自评难度 5：需要局部域的分歧理论 + log/exp + 类域论的标准不等式，是总决赛代数里最「研究生课」的一题。')
o()

o('### R3 · 2025 · 代数与数论 · Individual · Question 4（平方和层次 l(K)）')
o()
o('出处：BT./corpus/finals/..._Individual_2025_Algebra_Individual.txtBT（文字层完好）')
o()
o('> Question 4. Let K be a field, we define l(K) to be the smallest natural number n such that there are n')
o('> elements x_1, ..., x_n in K satisfying −1 = x_1² + x_2² + · · · + x_n². If no such n exists, we denote l(K) by ∞.')
o('> 1. Prove that l(K) = l(K(t)), here K(t) is the field of rational functions with coefficients in K.')
o('> 2. Compute l(K) when K are the following fields: Q(e^{2iπ/3}), Q(e^{2iπ/3}, 2^{1/3}).')
o()
o('**解题思路**')
o('1. 这是形式实域/二次型层次（level of a field，经典结果是 level ∈ {1,2,4,8,…} 或 ∞）的竞赛化版本。')
o('2. 第一部分：l(K(t)) ≤ l(K) 显然（常数解）。反向用**赋值/首项系数**论证：')
o('   若 −1 = Σ f_i(t)² 于 K(t)，取一个赋值（t 的阶）使某项在赋值下严格占优，则首项平方和不可能抵消为 0，矛盾。')
o('   等价的说法：K(t) 的 t-进赋值是实赋值，形式实域的有理函数域仍形式实。')
o('3. 第二部分（两个具体域）——可以用同一条恒等式处理：')
o('   - 关键观察：设 ω = e^{2πi/3}，则 ω² + ω + 1 = 0，即 **−1 = ω + ω²**；')
o('     而 ω 与 ω² 在 Q(ω) 中都是平方：ζ_6 = e^{iπ/3} = −ω² ∈ Q(ω)，且 (ζ_6)² = ω、(ζ_6²)² = ω²。')
o('     于是 −1 = (ζ_6)² + (ζ_6²)² 已是**两个平方之和**，故 l(Q(ω)) ≤ 2；')
o('     又 i ∉ Q(ω)（Q(ω) = Q(√−3) 不含 √−1），故 −1 不是平方，l(Q(ω)) = **2**。')
o('   - K = Q(ω, 2^{1/3})：上面的 ω、ω² 仍是 K 中的平方，所以 l(K) ≤ 2；')
o('     而 l(K) = 1 需要 −1 是平方（即 i ∈ K）。K 是 x³−2 的分裂域，Gal(K/Q) ≅ S_3，')
o('     其唯一指数 2 子群 A_3 对应唯一的二次子域 Q(ω)，因此 i ∉ K，l(K) = **2**。')
o('   （**抽取存疑**：第 2 问两个域的写法在 PDF 抽取中为 `Q(e2iπ/3), Q(e2iπ/321/3)`，')
o('   可读作 Q(e^{2πi/3}, 2^{1/3}) 或 Q(e^{2πi/3}·2^{1/3})。上面按前一种记法给出推理；')
o('   若原意是后一种（即 Q(ω∛2)，一个三次域），则「l ≤ 2」的论证仍成立，但 l = 1 的排除理由需换成')
o('   「三次域不含 Q(i)」——结论同样是 2。引用前请以原卷为准。）')
o('4. 自评难度 4：需要知道「域的形式实性 ⟺ 存在序 ⟺ −1 不是平方和」这条链，以及有理函数域保序。')
o()

o('### R4 · 2018 · 代数与数论 · Team · Problem 1（Chevalley–Warning）')
o()
o('出处：BT./corpus/finals/..._Team_2018_Algebra_Team.txtBT（文字层完好）')
o()
o('> Let d_i (1 ≤ i ≤ n) be positive integers such that Σ_{i=1}^{n} 1/d_i > 1.')
o('> For a prime number p, let F_p be the finite field of p elements. For')
o('>')
o('> f(x_1, · · · , x_n) = x_1^{d_1} + x_2^{d_2} + · · · + x_n^{d_n},')
o('>')
o('> prove that the number')
o('>')
o('> N := #{(x_1, · · · , x_n) ∈ F_p^n | f(x_1, · · · , x_n) = 0}')
o('>')
o('> is divisible by p. Hint: consider the sum Σ_{(x_1,···,x_n) ∈ F_p^n} f(x_1, · · · , x_n)^{p−1}.')
o()
o('**解题思路**')
o('1. 这是 **Chevalley–Warning 定理**的标准证明路线，题干给了提示。')
o('2. 记 S = Σ_x f(x)^{p−1}。在 F_p 中 f(x)^{p−1} 当 f(x) ≠ 0 时为 1，f(x)=0 时为 0，')
o('   所以 S ≡ #(非零点) = p^n − N (mod p)。若能证 S ≡ 0，则 N ≡ 0 (mod p)。')
o('3. 展开 f^{p−1} = (Σ x_i^{d_i})^{p−1}，得到形如 Π x_i^{e_i d_i} 的单项式之和，')
o('   其中 Σ e_i = p−1。每个单项式的全空间和 Σ_{x∈F_p^n} Π x_i^{e_i d_i} 是乘积 Σ_{x_i} x_i^{e_i d_i}；')
o('   而 Σ_{x ∈ F_p} x^m = 0 除非 m > 0 且 (p−1) | m（此时等于 −1）。')
o('4. 于是只有那些「所有 e_i d_i 都是 (p−1) 的正倍数」的项才可能非零；')
o('   由 Σ 1/d_i > 1 可证这样的项不存在（因为那要求 Σ e_i ≥ Σ (p−1)/d_i > p−1，与 Σ e_i = p−1 矛盾）。')
o('5. 因此 S = 0，N ≡ 0 (mod p)。自评难度 4：技巧全在「有限域上单项式求和」这一个引理。')
o()

o('### R5 · 2019 · 分析与微分方程 · Team · Question 3（Burgers 方程的全变差估计）')
o()
o('出处：BT./corpus/finals/..._Team_2019_Analysis_Team.txtBT（文字层完好）')
o()
o('> Consider the Cauchy problem for the Burger\u2019s equation (B):')
o('>')
o('> $$\\partial_t u + u\\partial_x u = \\epsilon \\partial_x^2 u, \\quad x \\in \\mathbb{R},\\ t > 0; \\qquad u(x, t = 0) = u_0(x)$$')
o('>')
o('> where ε ∈ (0, 1) is a constant, and u_0(x) is a smooth periodic function of period 1.')
o('> (1) Prove that if u^ε(x, t) is a solution to (B), then u^ε(x, t) is uniformly bounded independent of ε.')
o('> (2) Prove that the solution u^ε(x, t) is periodic in x with period 1.')
o('> (3) Show that if u^ε(x, t) is a solution to (B), then ∂_x u^ε(x, t) ≤ 1/t for all x ∈ R, t > 0.')
o('> (4) Show that the total variation of u^ε(x, t) in x is uniformly bounded independent of ε for t > 0,')
o('>     i.e. TV_{[0,1]} u^ε(x, t) ≤ C(t).')
o('> (5)(*) Discuss the convergence property of u^ε(x, t) as ε → 0+.')
o()
o('**解题思路**')
o('1. (1) 是标量守恒律的标准 **极大值原理**：u_t + u u_x = ε u_xx 在极值点处 u_xx ≤ 0、u_x = 0，')
o('   故 max|u| 不随时间增加，一致界就是 ‖u_0‖_∞。')
o('2. (2) 用**初值周期性的唯一性**：把 u(x+1,t) 与 u(x,t) 看成两个解，初值相同 ⟹ 解相同（抛物方程唯一性）。')
o('3. (3) 是 **Hopf 引理/导数下界**：对 v = ∂_x u 求导得 v_t + u v_x + v² = ε v_xx，')
o('   在 v 的最大值点处 v_x=0、v_xx ≤ 0，得 d/dt v_max ≤ −v_max²，解常微分不等式得 v ≤ 1/t。')
o('4. (4) 由 (3) 与 (1)：TV 的负变差被「单调下降段的总下降量」控制，')
o('   TV(u) ≤ 2 max|u| + ∫(正变差) ≤ 2‖u_0‖_∞ + (1/t)·(周期长度)，故 TV ≤ C(t) 且与 ε 无关。')
o('5. (5) 是开放题，指向 ε → 0 时解收敛到熵解（无粘极限）。')
o('6. 自评难度 5：五个小问把「最大值原理 → 抛物唯一性 → 导数界 → BV 估计 → 无粘极限」串成一条完整链条，')
o('   是 Team 卷「引导式长题」的典型。')
o()

o('### R6 · 2025 · 分析与微分方程 · Individual · Problem 2（Phragmén–Lindelöf 型边界估计）')
o()
o('出处：BT./corpus/finals/..._Individual_2025_Analysis_Individual.txtBT（文字层完好）')
o()
o('> Let Ω = { x + iy ∈ C : x > 0, y > 0 }. Assume that f : Ω → C is a bounded continuous function on Ω')
o('> and holomorphic on Ω such that')
o('>')
o('> ∀x ∈ [0, +∞], max{|f(x)|, |f(ix)|} ≤ { 2 if x ≤ 1; 1 if x > 1 }.')
o('>')
o('> Show that ∀x + iy ∈ Ω, |f(x + iy)| ≤ 2^{(2/π) arctan(1/(2xy))}.')
o()
o('**解题思路**')
o('1. Ω 是第一象限（角域，开口 π/2）。边界条件只有**两条正半轴**上「以 1 为界、在 [0,1] 段放宽到 2」。')
o('2. 标准工具是 **Phragmén–Lindelöf / 调和测度**：右端指数 (2/π)·arctan(1/(2xy)) 恰是')
o('   角域边界上「哪一段可见」的调和测度（= 共形映射到条带后的 Poisson 核权重）。')
o('3. 做法：把 Ω 用 z ↦ z² 映到上半平面（角域 → 半平面），此时边界条件变成上半平面实轴上的两段界：')
o('   |z| ≤ 1 段给 2、|z| > 1 段给 1；再用上半平面的 Poisson 公式/次调和函数比较，')
o('   得到 log|f| 不超过边界势的调和延拓，即 log|f(w)| ≤ (2/π)·arctan(1/(2xy))·log 2。')
o('4. 指数化即得结论；关键是把 arctan 项识别成「从点 (x,y) 看 [0,1] 段的视角/调和测度」。')
o('5. 自评难度 5：需要会「把角域映成半平面 + 用调和测度把边界数据加权」，是总决赛分析卷近年最难的构型题之一。')
o()

o('### R7 · 2018 · 分析与微分方程 · Team · Problem 1（等周不等式与 Steiner 对称化）')
o()
o('出处：BT./corpus/finals/..._Team_2018_Analysis_Team.txtBT（文字层完好，原文分 3 步）')
o()
o('> 1. Isoperimetric inequality and Steiner symmetrization.')
o('> It is well known that in R², any region Ω with continuous piecewise C¹ boundary ∂Ω satisfies that')
o('> 4π|Ω| ≤ Length(∂Ω)². When the equality holds ..., it is then called an isoperimetric set.')
o('> For example, all disks are isoperimetric sets.')
o('> 1) Prove that any isoperimetric set is convex;')
o('> 2) Given a line V in R² passing through the origin, the Steiner symmetrization with respect to V is the')
o('>    operation which associates with each bounded convex subset C of R² the subset S(C) of R² such that,')
o('>    for every line L perpendicular to V, either L ∩ C = ∅ and L ∩ S(C) = ∅, or L ∩ C ≠ ∅ and L ∩ S(C)')
o('>    is a closed segment with center in V, and Length(L ∩ S(C)) = Length(L ∩ C).')
o('>    Prove that |S(C)| = |C|, and Length(∂S(C)) ≥ Length(C), equality holds if and only if C is symmetric')
o('>    with respect to V.')
o('> 3) Deduce that the only isoperimetric sets are the disks.')
o()
o('**解题思路**')
o('1. (1) 若等周集 Ω 不凸，取凸包：凸包面积变大（若真有凹陷）而周长不增，与等周等式矛盾。')
o('2. (2) 面积不变是 Fubini（每条垂直线上线段长度不变）；周长不减需要把周长拆成')
o('   「与 V 垂直的边」与「两个函数图像（上半/下半边界）」，')
o('   前者按构造不变，后者用一元函数的**变差/弧长**在「把两端点向中线压缩」下不增（等号 ⟺ 每层对称）来证。')
o('3. (3) 反复做不同方向 V 的 Steiner 对称化，面积不变、周长不增，序列收敛到圆盘（对称化 + 紧性），')
o('   结合 (1) 的凸性，得到等周集只能是圆盘。')
o('4. 自评难度 4：这是一道「把一个经典定理拆成可验证步骤」的证明题，计算量大但每一步都是标准工具。')
o()

o('### R8 · 2024 · 分析与微分方程 · Individual · Problem 2（热/波方程解的水平集与传播）')
o()
o('出处：BT./corpus/finals/..._Individual_2024-_Analysis_Individual-new1.txtBT（文字层完好，原文分 (i)(a)(b)(ii)）')
o()
o('> (i) Consider the following Cauchy problem:')
o('>')
o('> $$u_t - (a(x)u_x)_x = 0 \\quad \\text{for } x \\in \\mathbb{R},\\ t > 0, \\qquad u|_{t=0} = u_0(x),$$')
o('>')
o('> where a(x) ∈ C² is bounded with a(x) ≥ a_0 > 0.')
o('> (a) Let u(x, t) be the solution with u_0(x) = 1 for x ∈ [−1, 1], 0 otherwise.')
o('>     Does u(x, t) have zero points on the line t = 1/1000? Explain your reasons.')
o('> (b) Is it possible to prepare some bounded initial data u_0(x) such that the solution becomes')
o('>     u(x, 1) = 1 for x ∈ [−1, 1], 0 otherwise, at t = 1? Explain your reasons.')
o('> (ii) Consider the following Cauchy problem:')
o('>')
o('> $$u_{tt} - (a(x)u_x)_x = 0, \\qquad u|_{t=0} = u_0(x),\\ u_t|_{t=0} = 0,$$')
o('>')
o('> with the same u_0. Does u(x, t) have zero points on the line t = 1000? Explain your reasons.')
o()
o('**解题思路**')
o('1. 三个小问考的是**同一件事的不同侧面：解在多大范围内「记得」初值**。')
o('2. (i)(a) 抛物方程具有**无穷传播速度**：热核在任意正时刻都有全支撑。u_0 ≥ 0 且不恒为 0，')
o('   故 t = 1/1000 时 u(·, t) > 0 处处成立（用极大值原理证：若某点取 0，则与正初值矛盾）→ **没有零点**。')
o('3. (i)(b) 不可能。方向相反：解算子把非负初值磨成处处正的函数，')
o('   而目标函数在 [−1,1] 外取 0，在其边界处不满足抛物方程的正则性/无穷传播速度蕴含的严格正性 → 矛盾。')
o('4. (ii) 波动方程具有**有限传播速度**（c = √(a(x)) 有正上下界）：')
o('   t = 1000 远大于支撑传播所需时间，故依赖域内的信息早已离开，')
o('   u(·, 1000) 在 [−1,1] 的传播锥之外恒为 0 → **有零点**。')
o('5. 自评难度 4：每个小问都只需一条定性原理（无穷传播速度 vs 有限传播速度），')
o('   但要在「是否有零点」这个很弱的问题上把它用对，需要对两套方程的性质分得非常清楚。')
o()
o('> **抽取说明**：2024 ANA Individual 的 PDF 抽取在第 2 页末尾把 「in B \\ {0}」 一行错位到文末，')
o('> 该错位不影响本题题面。')
o()

o()
o('---')
o()
o('## 7. 存疑与无法分析清单')
o()
o('### 7.1 完全无法分析（放弃）')
o()
o('| 出处 | 内容 | 原因 |')
o('|---|---|---|')
o('| 2012 ANA Individual #2 | 整函数与其迭代的题 | 源为 .doc，公式全是 OLE 对象，条件（f 的规范化、迭代估计）全部丢失 |')
o('| 2014 ANA Individual #3 | 「对素数全体证明级数发散」 | 级数本身丢失，只剩结论文字 |')
o('| 2014 ANA Individual #5 | (a)(b) 两个小问 | 题面公式全丢，只剩 a) b) 两行 |')
o('| 2013 ANA Team #2 | 无内容 | 原 Word 文件里只有标题 |')
o()
o('### 7.2 分析但需存疑')
o()
o('| 出处 | 存疑点 | 处理 |')
o('|---|---|---|')
o('| 2015 ALG Individual / Team / Overall | 无文字层或 CJK 字体损坏，本报告的题面由**渲染后人工识读**得到 | 题面按识读结果录入；个别符号（如 Z[w]/(1−w)、‖M‖=sup 的写法）以原卷渲染图为准 |')
o('| 2014 ALG Team #1、#2 | .docx 抽取把 α, β 的作用式与矩阵 J 打散 | 描述中标「题面公式经抽取后残缺，按上下文重排」 |')
o('| 2025 ALG Individual #4 第 2 问 | e^{2iπ/3} 与 e^{2iπ/3}·2^{1/3} 的域记号在抽取中略糊 | 结论依赖记号判读，已在 R3 标注 |')
o('| 2018 ANA Individual #5 | 抽取出的 (c) 与 (d) 两小问文字**完全相同** | 疑为原卷排版重复或抽取重复；本题仍按 5 题计入，但小问数（记为 1 题）不变 |')
o('| 2020 ALG Individual | 两页各自从 Problem 1 重新编号 | 本报告合为 1 卷 6 题（页 1 三题 + 页 2 三题）；若按两卷计则卷数会变化 |')
o('| 2013 ALG Individual #2 | 题面写「polynomials with both x, y-degrees at most k」但变量用 m, n | 原文即如此，未改动 |')
o('| 2021 ANA Overall | 文件被索引为 Overall，但**卷面自称 Group Contest** | 报告按索引归入 Overall；实际可能是 Team 轮，属原始语料元数据不一致 |')
o('| 2017 ALG Individual 等 7 卷 | 抽取出现 BTBT 与 ă 等连字/字体替换残留（如 K “ Qpe^{2πi/m}q） | 已在引用时按语义还原，未改结构 |')
o('| 全部恢复集 | 公式缺失 | 已在 §2.2 逐行标注「公式缺失」 |')
o()
o('### 7.3 语料层面的缺口（不是分析失败，是文件不存在）')
o()
o('| 年份 | 缺失卷 |')
o('|---|---|')
o('| 2012–2014 | ANA Individual 原本为 .doc/.docx（本报告已恢复）；ANA Team、ANA Overall 的 2012 年缺 |')
o('| 2014 | ALG Team 原本为 .docx（已恢复）；ALG Overall 2014 缺失 |')
o('| 2013、2014 | ALG Overall 缺（F 盘无对应文件） |')
o('| 2020–2022 | ALG Team 与 ANA Team 全部缺失（连续三年） |')
o()
o('### 7.4 与本报告无关但影响横向比较的既有报告问题')
o()
o('- BT./reports/problem_metrics.mdBT 的难度是「长度+小问+符号密度」的启发式代理，与本题库的人工自评**不可直接比较**，')
o('  本报告在 §4 只把它当方向性证据，并明确标注口径差异。')
o('- 既有笔试报告统计的是 2010–2026 的**笔试**语料，其「混合/Team（多科目）」类目的是按卷切的，')
o('  与总决赛按科目切分的 Team 卷不可直接对齐；本报告的对比只取可以对齐的口径（题量、词数、动词、考点）。')
o()

o()
o('---')
o()
o('## 关键数字摘要')
o()
o('1. 分析范围：代数与数论/组合 + 分析与微分方程，总决赛 **73 卷 / 244 题**（PDF 主集 66 卷 215 题 + 从 .doc/.docx 恢复 7 卷 29 题）。')
o('2. 全语料 195 个 txt 中 chars<800 有 65 个，但**真正无文字层**在本范围只有 1 卷（2015 ALG Overall，0 字符 / 11 张图）；')
o('   另有 2 卷 CJK 字体损坏（2015 ALG Individual、Team）。三卷已渲染后人工识读，补回 8 题。')
o('3. 新发现：**7 卷真题从未被原管线转换**（2014 ALG Team、2012/2013/2014 ANA Individual、2013/2014 ANA Team、2013 ANA Overall），')
o('   本报告首次恢复，把分析科目的覆盖从 2015 年提前到 **2012 年**。')
o('4. 卷别结构：Individual 28 卷 116 题（4.14 题/卷）、Team 21 卷 74 题（3.52 题/卷）、Overall 24 卷 54 题（2.25 题/卷）。')
o('5. 考点前五：linear 33、pde 33、real 30、cplx 28、comm/ant 各 18（rep 16、harm 16、group/func 各 15）。')
o('6. 难度自评：均值 **3.32**；=5 共 18 题、≥4 占 38%；Team 卷最难（3.56，≥4 占 50%），Individual 最平（3.18，≥4 占 30%）。')
o('7. 与笔试差异 1：笔试只有 Individual/Team 两类卷，总决赛多出 **Overall（All-round）24 卷 54 题，占 22% 的题量**。')
o('8. 与笔试差异 2：题量密度 笔试 6.32 题/卷 vs 总决赛 **3.34 题/卷**（约为一半）。')
o('9. 与笔试差异 3：总决赛基本是纯证明卷——ALG 全文 prove 63 / show 42，而 compute+calculate 仅 4 次（prove+show 占 88%）。')
o('10. 与笔试差异 4：题长 ANA 49 → **56.5 词/题**（+15%），ALG 84 → **61 词/题**（−27%）。')
o('11. 与笔试差异 5：总决赛显著抬高 PDE（27→33 题次）与调和分析，并新出现波动/色散、遍历论、p 进局部域等笔试几乎不考的考点。')
o('12. 与笔试差异 6：出现 **Oral/ORAL 字样的卷 6 卷**、All-round/Overall 11 卷、Final Contest 3 卷——总决赛是口试。')
o('13. 与笔试差异 7：总决赛 **7 卷有「选做」机制**（2021 ANA Individual 两题 optional；2023 三卷；2025 三卷），笔试没有。')
o('14. Individual vs Team：Team 平均难度 3.56 > Overall 3.30 > Individual 3.18；ANA Team 最高（**3.64**）。')
o('15. Individual vs Team：题面长度 Team 最长（ANA Team **71.5 词/题** vs ANA Individual 50.6）。')
o('16. Individual vs Team：Team 卷偏爱「a)–d) 分步引导 + Hint」（2013 ALG Team #1、2018 ANA Team #1、2019 ALG Team #4 等）。')
o('17. Individual vs Team：**2020–2022 连续三年两个科目都没有 Team 卷**（F 盘目录核实确无文件）。')
o('18. 官方解答：本范围只有 **2021 ALG Individual 与 2021 ALG Overall** 两卷随卷附官方解答（原文件名带 (S)）。')
o('19. 语料缺口：ALG Overall 缺 2013、2014；ALG Team 缺 2014、2020、2021、2022；ANA Team 原本缺 2012–2014（已从 Word 恢复）、缺 2020–2022。')
o('20. 全部题面均可追溯到 BT./corpus/finals/BT 或 BT./corpus/finals_extra/BT 的具体文件；本题库与统计脚本见')
o('    BT./scripts/finals_alg_ana_problems.pyBT、BTfinals_alg_ana_extras.pyBT、BTfinals_final_stats.pyBT、BTgen_report.pyBT。')
o()

open(OUT, 'a', encoding='utf-8').write('\n'.join(L).replace('BT', chr(96)) + '\n')
print('appended lines:', len(L))
