# -*- coding: utf-8 -*-
"""丘成桐大学生数学竞赛 总决赛 2012-2025 · 代数/数论/组合 + 分析与微分方程
人工逐题标注数据库（题面均来自 .tmp/burn2026/txt_finals 抽取文本；2015 代数三卷为
图片/乱码卷，经 fitz 渲染后人工识读）。
字段：(年份, 科目, 卷别, 题号, 一句话题意, 子领域标签, 核心定理/方法, 难度1-5)
科目: ALG / ANA ；卷别: Individual / Overall / Team
"""
P = [
# ---------------- ALG Individual ----------------
(2012,'ALG','Individual','1','k 域上 GL2(k) 中上三角子群 B 的 B×B-轨道分类（(b1,b2)·g=b1gb2^{-1}）','linear,ag','Bruhat 分解 / 双陪集',3),
(2012,'ALG','Individual','2','证明 det(I−AB)=det(I−BA)','linear','Sylvester 行列式恒等式',1),
(2012,'ALG','Individual','3','求所有 Q-代数 R 使 R[X,Y] 中 X²+Y²=(aX+bY)²','comm,quad','二次型 / 环上分解',4),
(2013,'ALG','Individual','1','循环图 (Z/fZ) 上满足 Orpheus 条件 (φψ=ψφ=0) 的线性映射族，证存在不变直线 ℓ_i','linear,rep','箭图表示 / 归纳法',4),
(2013,'ALG','Individual','2','V_k=R[x]_{≤k} 上 SL2(R) 作用的不可约性、正合列分裂与不变量维数','rep','Clebsch–Gordan 分解',3),
(2013,'ALG','Individual','3','(x²+3)(x³+2) 是否对每个素数 p 都有 mod p 解','ant,poly','二次/三次互反律、Chebotarev',4),
(2014,'ALG','Individual','1','解 End k^n 中的方程 x²=x','linear','幂等元 / 投影分类',2),
(2014,'ALG','Individual','2','构造 Q 上 Galois 群为 Z/nZ 的 Galois 扩张','galois,field','分圆域',2),
(2014,'ALG','Individual','3','p>3 时 x³+y³=1 在 Z/pZ 的解数；p≡1(3) 时 4p=a²+27b² 与解数 p−2+a','ant','Jacobi 和 / 三次剩余 / Gauss 定理',5),
(2015,'ALG','Individual','1','GL_n(R) 中含于开单位球 B(I,1) 的子群 G 必为 {I}（特征值 |λ−1|<1）','linear','谱半径 / 矩阵范数',3),
(2015,'ALG','Individual','2','GL_n(Z)→GL_n(F_p) 在有限子群上单射；GL_2(Z) 有限阶元 m∈{1,…,6}','group','模群 / 有限阶分类',2),
(2015,'ALG','Individual','3','R(x) 中在整数上取整值的函数必为多项式','comm,poly','整值多项式 / 有限差分',3),
(2016,'ALG','Individual','1','x⁴−4x²−1 的分裂域：不可约性与 Galois 群','galois','四次域 / 群阶判定',3),
(2016,'ALG','Individual','2','代数闭包 F̄_p^× 的初等描述与 Frobenius 的作用','field','有限域 / Prüfer 群',3),
(2016,'ALG','Individual','3','A,B∈M_n(Q) 在 Q 上相似 ⟺ 在 C 上相似','linear','有理标准形 / 不变量因子',2),
(2017,'ALG','Individual','1','分类 8 阶群及其 C 上不可约表示','group,rep','群分类 / 特征标表',3),
(2017,'ALG','Individual','2','x⁴+x³+x²+x+1 不可约；Gal(Q(ζ5)/Q) 循环；Gal(Q(ζ20)/Q)≅(Z/20Z)^×','galois','分圆多项式 / Eisenstein',3),
(2017,'ALG','Individual','3','R=C[x]/(f)：R 无幂零元 ⟺ 有限生成不可分解 R-模投射','comm,homol','交换代数 / Nakayama',4),
(2018,'ALG','Individual','1','把 6x⁵+3x⁴−9x³+15x²−13x−2 分解为 Q[x] 中不可约因子','poly','有理根定理 / 模 p 不可约',2),
(2018,'ALG','Individual','2','证明 588 阶群可解（已知 12 阶群可解）','group,sylow','Sylow 定理 / 正规子群链',3),
(2018,'ALG','Individual','3','判定哪些域 F 使任意 n×n 矩阵都可上三角化','linear,field','特征多项式分裂 / 代数闭性',2),
(2018,'ALG','Individual','4','求 A↦A^tA 在 M_n(C) 与 M_n(R) 上的像','linear','半正定 Hermite / 谱分解',3),
(2018,'ALG','Individual','5','k(x,y)/k(x^p,y^p) 的次数为 p²，且中间域有无穷多个','field','纯不可分扩张 / 模 p 独立',3),
(2019,'ALG','Individual','1','GL(m,R) 中 g=k1 d k2（正交×正对角×正交）','linear','极分解 / SVD',2),
(2019,'ALG','Individual','2','首一不可约 P∈Q[X] 的根单；存在特征多项式为 P 的整数/有理矩阵','linear,poly','伴侣矩阵 / 结式',3),
(2019,'ALG','Individual','3','48 阶群不可能是单群','group,sylow','Sylow 计数 / 单群判定',3),
(2019,'ALG','Individual','4','Fibonacci 矩阵 A 在 Q、F2、F5 上的分裂域与半单性；lim f_n^{1/n}=黄金比','linear,field','分裂域 / 二次剩余 / 周期',3),
(2019,'ALG','Individual','5','k 无限域、K/k 扩张：A,B 在 K 上相似 ⟹ 在 k 上相似','linear','有理标准形 / 域下降',2),
(2020,'ALG','Individual','1','R={f∈C[x]:f′(0)=0} 是否为有限生成 C-代数','comm','不变量子环 / 有限生成性',3),
(2020,'ALG','Individual','2','exp 把幂零矩阵一一映到幺幂矩阵；逆的描述与 exp 的像','linear','矩阵指数 / Jordan 形',3),
(2020,'ALG','Individual','3','Gauss 和 G_d=Σ_{x∈F_p}ζ_p^{x^d} 在 Q 上的次数等于 (d,p−1)','ant','分圆域 / 特征和',4),
(2020,'ALG','Individual','4','A_ij=ζ^{ij}−ζ^{(i−1)j}：det(A)²∈Z，且 d≡0,3 (mod 4) 时 det(A)∉Z','ant,linear','Vandermonde 型行列式 / 分圆整数',4),
(2020,'ALG','Individual','5','特征 ≠2 的域上奇数阶正交矩阵有特征值 det(M)','linear','正交群 / 行列式',2),
(2020,'ALG','Individual','6','GL_n(Z) 的有限子群阶数存在仅依赖 n 的一致上界 c_n','group,rep','Minkowski 界 / 平均技巧',3),
(2021,'ALG','Individual','1','Q_p(ζ_{p^n}) 的范数映射 N_{L/Q_p}(L^×) 的像','padic,ant','局部域 / 类域论 / log-exp',5),
(2021,'ALG','Individual','2','φ:GL(V)→GL(∧²V) 的核与 det(∧²f)=det(f)^{n−1}','linear,rep','外幂 / 初等矩阵',3),
(2021,'ALG','Individual','3','分类 Z⁵/AZ³（A 为 5×3 秩 2 整矩阵）','homol,linear','Smith 标准形 / 有限生成模',3),
(2022,'ALG','Individual','1','求所有满足 σ(AB)=σ(BA) 且 σ(I)=n 的 C-线性泛函 σ','linear','迹的唯一性 / 交换子空间',3),
(2022,'ALG','Individual','2','p 进域 O_F 中元素表为平方和：p≠2 三个平方，Q_2 四个平方','padic,quad','局部域 / Hilbert 符号',4),
(2022,'ALG','Individual','3','R=∏_p F_p：存在极大理想使商域特征 0 且 −1 非平方；不存在 R/n↪R','comm,field','超积 / Artin–Schreier / 形式实域',4),
(2023,'ALG','Individual','1','(1) 数 (Z/pZ)^n 的 p^k 阶子群个数；(2) 分类 Z⁵/AZ^n（二选一）','group,linear','子群格 / Smith 标准形',3),
(2023,'ALG','Individual','2','n 个两两交换的幂零自同态之复合 u_1∘…∘u_n 的性质','linear','同时三角化 / 幂零性',3),
(2023,'ALG','Individual','3','证明 dim V^G=(1/|G|)Σχ(g) 与 Molien 公式 Σdim(S^G∩S_d)t^d','rep,comm','特征标平均 / 不变量环',3),
(2024,'ALG','Individual','1','H≤G，(|H|,[N_G(H):H])=1 ⟹ N_G(H)=N_G(N_G(H))','group','Burnside 正规 p-补 / Frattini 论证',4),
(2024,'ALG','Individual','2','F-开集是否总构成 F̄^n 上的拓扑','ag','Zariski 拓扑 / 下降',4),
(2024,'ALG','Individual','3','关系 a_ib_j±b_ja_i=δ_ij 生成的代数的单模分类（Clifford / Weyl 代数）','rep,comm','Clifford 代数 / Weyl 代数 / Schur 引理',4),
(2024,'ALG','Individual','4','A=C[t,t^{−1}]，γ:f(t)↦f(−1/t) 的不动子环 R 及其性质','comm','不变量 / UFD 与 PID',4),
(2025,'ALG','Individual','1','GL_n(R) 共轭作用在对角矩阵上的轨道是闭集','linear,ag','轨道闭性 / 特征多项式',3),
(2025,'ALG','Individual','2','有限阿贝尔群范畴既无足够投射也无足够内射对象','homol,cat','范畴论 / 可除群',3),
(2025,'ALG','Individual','3','|G|=n ⟹ |Aut(G)| ≤ n^{log_2 n}','group','生成元个数 / 次正规列',3),
(2025,'ALG','Individual','4','平方和层次 l(K)：证明 l(K)=l(K(t)) 并计算两个数域的值','quad,field','二次型 / 形式实域 / 域扩张',4),
# ---------------- ALG Overall ----------------
(2012,'ALG','Overall','1','P¹ 上 6 点分支的双覆盖 C：分类其无分支 7-循环覆盖 D 及中间曲线','ag,galois','Riemann 面 / Hurwitz 公式 / 覆盖理论',4),
(2015,'ALG','Overall','1','P∈Z[x] 为 k 次本原多项式，d(P)=gcd{P(a):a∈Z} 整除 k!','poly,ant','整值多项式 / 有限差分',3),
(2015,'ALG','Overall','2','存在 M_n(C) 的基 {X′_i} 使 Tr(X_iX′_j)=δ_ij 且 ΣX_iAX′_i=Tr(A)I_n','linear','迹形式 / 对偶基',3),
(2016,'ALG','Overall','1','Q(ζ_{p^n}) 的唯一二次子域；p=2,n≥3 时二次子域个数与具体域','ant,galois','分圆域 / Gauss 和',4),
(2017,'ALG','Overall','1','有限域阶 p^n；二次互反律；691 素数时 439 非二次剩余；x²+6x+1 双根的 p','ant','二次互反律 / Legendre 符号',3),
(2017,'ALG','Overall','2','GL_2(F_p) 中幺幂上三角子群是 Sylow p-子群并数其个数','group,sylow','Sylow 定理 / 阶计算',3),
(2018,'ALG','Overall','1','N=∏_{(i,n)=1}(1−ζ_n^i)：n 为素数幂时等于 p，否则等于 1','ant','分圆域 / 范数 / 单位',4),
(2018,'ALG','Overall','2','GL_2(F) 的 B×B 双陪集恰两个轨道（对角与反交换），推广到 GL_n','linear,ag','Bruhat 分解 / 双陪集',3),
(2018,'ALG','Overall','3','描述所有可嵌入 M_n(Q) 的域扩张 K','comm,field','中心单代数 / 分裂域',4),
(2018,'ALG','Overall','4','X={V⊃E:dim V=m} 是否紧流形、维数几何、是否齐性空间','ag','Grassmann 流形 / 齐性空间',3),
(2019,'ALG','Overall','1','构造有 p−2 个实根与 2 个复根的 p 次不可约多项式（P_k=kp²P_0+X^p−p）','poly','摄动 / 一致收敛 / 实根计数',4),
(2019,'ALG','Overall','2','L=k(x,y)（x²+y²=1）在 k 上的 Galois 群','galois,field','有理函数域 / 二次扩张',3),
(2019,'ALG','Overall','3','存在 u∈V* 稳定子平凡；φ_u:S(V)→C[G] 满射；忠实不可约表示嵌入 S^n(V)','rep','不变量论 / 特征标 / 分裂域',4),
(2020,'ALG','Overall','1','任何有限阿贝尔群都是 Q 的某个 Galois 扩张的 Galois 群；非阿贝尔例子','ant,galois','Kronecker–Weber / 逆 Galois 问题',3),
(2020,'ALG','Overall','2','SL_2(F_p) 的阶、Sylow p-子群个数、M_{a,b} 共轭类判定与个数','group,sylow','Sylow 定理 / 共轭类',4),
(2021,'ALG','Overall','1','上三角矩阵代数 A 的所有单模有限维且恰为 n 个一维模','rep,homol','Jacobson 根 / Schur 引理',3),
(2021,'ALG','Overall','2','Euler 定理：p=x²+3y² 有解 ⟺ p=3 或 p≡1 (mod 3)','ant,quad','二次互反 / Z[ω] 的 PID 性',3),
(2022,'ALG','Overall','1','C[x,y]/(x²+y²−1) 是 UFD，而 R[x,y]/(x²+y²−1) 不是','comm,ag','唯一分解 / 类群 / 实点',4),
(2022,'ALG','Overall','2','f=x³−x−1：f 在 F_p 恰一根 ⟺ (p/23)=−1；求分裂中 e,f,g','ant,galois','三次域判别式 / 分裂类型',4),
(2023,'ALG','Overall','1','把 Z[x1,x2,x3]/(x1x2+x3²−2) 写成系数全为 1、次数≤2 的平方自由多项式商；一般情形？','comm,ag','Gröbner 基 / 二次型配方',3),
(2024,'ALG','Overall','1','G 是 p-群 ⟺ 每个非零 k-表示（char k=p）有非零不动点','rep','模表示 / 不动点函子',3),
(2024,'ALG','Overall','2','构造微分同胚 GL_3(R)→O(3)×R⁶，并给出 GL_n(C) 的类比','linear','极分解 / QR 分解',3),
(2025,'ALG','Overall','1','非阿贝尔有限 p-群满足 [G:G′] ≥ p²','group','交换子群 / p-群中心',3),
(2025,'ALG','Overall','2','对称双线性型 B 与单 Jordan 块幂零算子 T 满足 B(Tv,w)=−B(v,Tw) ⟹ n 为奇数','linear','辛结构 / Jordan 形',4),
# ---------------- ALG Team ----------------
(2012,'ALG','Team','1','SO(2) 作用 C[X,Y] 的不变量环为 C[X²+Y²]；Fourier 变换与 P(∂) 交换；C[∂x,∂y]^{SO(2)}','rep,harm','不变量论 / Fourier 变换 / 微分算子环',3),
(2012,'ALG','Team','2','Gal(Q(ζ7)/Q)；找 Galois 群为 Z/3Z 的扩张；Q(ζ7) 的二次子域','galois','分圆域 / Galois 对应',2),
(2013,'ALG','Team','1','tr(A^n)∈F (∀n≥2) ⟹ tr(A)∈F（分步引导：Newton 恒等式 + 特征值）','linear,field','Newton 恒等式 / 迹的域下降',3),
(2013,'ALG','Team','2','R[x,y]/(x²+y²−1) 不是 UFD；C[x,y]/(x²+y²−1) 是 PID','comm,ag','唯一分解 / 曲线的坐标环',3),
(2015,'ALG','Team','1','Z[w]/(1−w)≅F_p；φ∈F_p[x] 的根重数 < 非零系数个数；(w^{a_ib_j}) 可逆','ant,linear','分圆整数 / Vandermonde 型行列式',3),
(2015,'ALG','Team','2','复根 α 的实部非正或 |α|<(1+√(1+4H))/2；由 p 的 b-进制展开得到的多项式不可约','poly,ant','Cauchy 界 / Cohn 不可约性',4),
(2015,'ALG','Team','3','数值域 W(A)⊂△(z1,z2,z3) ⟺ A=z1A1+z2A2+z3A3（A_i 半正定，ΣA_i=I）','linear','数值域 / 半正定分解',4),
(2016,'ALG','Team','1','有限生成 Z-代数的极大理想的商是有限域','comm','Zariski 引理 / Nullstellensatz',3),
(2016,'ALG','Team','2','确定阿贝尔群范畴与群范畴的“中心”（恒等函子到自身的自然变换）','cat','范畴论 / Eckmann–Hilton',3),
(2016,'ALG','Team','3','Weyl 代数：char 0 无有限维表示；char p>0 时求所有有限维表示','rep,comm','Weyl 代数 / 中心 / 模 p 约化',4),
(2017,'ALG','Team','1','G=GL_2(C) 的有限维表示完全可约，并求所有不可约表示','rep','完全可约性 / 最高权',3),
(2017,'ALG','Team','2','K,L 为素数次扩张，[KL:Q]=[K:Q][L:Q] ⟹ 二者 Galois 闭包相同','galois,field','线性无关 / Galois 闭包',4),
(2017,'ALG','Team','3','极小非平凡正规子群 N ≅ L×…×L（L 单群）','group','正规子群 / 特征子群',3),
(2018,'ALG','Team','1','Σ1/d_i>1 时 x_1^{d_1}+…+x_n^{d_n} 在 F_p^n 上的零点数被 p 整除','field,comb','Chevalley–Warning 定理',4),
(2018,'ALG','Team','2','有限群 G 作用 k[x_1,…,x_n]，不变量子环 S 有限生成','comm,rep','Noether 有限性定理',3),
(2018,'ALG','Team','3','R=k[[t]]，v_i 的像构成 M/tM 的基 ⟹ {v_i} 是 M 的基','comm,homol','Nakayama 引理',3),
(2018,'ALG','Team','4','dim{AX−XA} ≤ n²−deg μ(t)，等号 ⟺ μ 的次数为 n','linear','交换子空间 / 极小多项式',4),
(2019,'ALG','Team','1','(a) 有 p−2 实根 2 复根的 p 次不可约多项式的分裂域 Galois 群为 S_p；(b) X⁵−6X+3 的 Galois 群','galois','Galois 群 / 传递群',4),
(2019,'ALG','Team','2','方程组的解集可写成单个多项式 P=0 的解集','comm,ag','理想 / Nullstellensatz / 乘积技巧',3),
(2019,'ALG','Team','3','K[X] 上 v_0-赋值给出 ultrametric，K[[X]] 为其完备化，K 有限时紧','valua','非阿基米德度量 / 完备化',4),
(2019,'ALG','Team','4','同余数：nm²=ab(a+b)(a−b) 判别；r∈{1,2,3,5,6,7} 有无穷多 n≡r (mod 8)','ant,quad','同余数问题 / 二次型 / 椭圆曲线',5),
(2019,'ALG','Team','5','投射模的 Schanuel 引理：K⊕P′ ≅ K′⊕P','homol','投射模 / 拉回构造',3),
(2023,'ALG','Team','1','Q/Z 中阶为 n 的子群唯一','group','可除群 / 挠子群',2),
(2023,'ALG','Team','2','S_k(d)=Σ_{x∈F_{p^k}}ζ_p^{Tr_k(x^d)}∈Z（d | (p^k−1)/(p−1)）','field,ant','特征和 / 迹映射 / Gauss 和',5),
(2024,'ALG','Team','1','求所有满足 A^T−I=A+A^{−1} 的可对角化可逆实特征值矩阵','linear','矩阵方程 / 谱',3),
(2024,'ALG','Team','2','P+Q=R 互素 ⟹ deg R < deg rad(PQR)','poly,ant','Mason–Stothers（多项式 abc）',4),
(2024,'ALG','Team','3','Ẑ 的子群开 ⟺ 有限指数；∏_N Z/pZ 是否同样成立','group','射有限群 / 拓扑群',4),
(2025,'ALG','Team','1','秩 k 矩阵循环延拓的指标函数 f_A 是双射，且 Σf_A(i)=C(n+1,2)+kn','linear,comb','组合恒等式 / 生成集',4),
(2025,'ALG','Team','2','X⁴+9 与 X⁸+9 在 Q_3 上不可约；X⁸+9 分裂域的次数','padic','Eisenstein / 局部域分歧',4),
(2025,'ALG','Team','3','GL_n(Z) 在同构意义下只有有限多个有限子群','group','Minkowski / 有界阶',3),
# ---------------- ANA Individual ----------------
(2015,'ANA','Individual','1','Σ 2^n sin(x/3^n) 绝对收敛但在任何 (0,ε) 上不一致收敛','real','级数一致收敛 / Dirichlet 判别',2),
(2015,'ANA','Individual','2','f∈C^(n)[0,1] 且 ∫f(t)t^j dt=0 (j=1..n) ⟹ ∃ξ, f^(n)(ξ)=0','real','正交性 / Rolle 定理迭代',3),
(2015,'ANA','Individual','3','单位盘到自身解析且在某段边界弧上为常数 ⟹ f 恒为常数；Jordan 域？','cplx','Schwarz 反射 / 唯一性定理',3),
(2015,'ANA','Individual','4','求所有满足 L*(E∩[a,b]) ≤ (b−a)/2 的集合 E','real','Lebesgue 外测度 / 密度',4),
(2016,'ANA','Individual','1.1','|f|≤1 于单位盘且 f(±1/2)=0 ⟹ |f(0)|≤1/4','cplx','Schwarz–Pick / Blaschke 乘积',3),
(2016,'ANA','Individual','1.2','a_n=sin(a_{n−1}) ⟹ Σa_n² 发散','real','渐近展开 / 比较判别',2),
(2016,'ANA','Individual','1.3','L^p[0,1] 范数满足平行四边形律 ⟺ p=2','func','内积 / Clarkson 不等式',2),
(2016,'ANA','Individual','1.4','上半平面 Laplace 方程、阶跃边界数据的全部有界解','pde,potential','Poisson 积分 / 调和函数',3),
(2016,'ANA','Individual','1.5','∀a, f(x+a)−f(x)→0 ⟹ f=g+h, g→0, h′→0','real','分解 / 一致连续性',4),
(2016,'ANA','Individual','1.6','|a_n|≤K/|n| 时 Fourier 部分和的一致界 sup|f|+2K','harm','Dirichlet 核 / 部分和估计',3),
(2017,'ANA','Individual','1','单调递减权 g 下的加权平均不等式 ∫xfg/∫fg ≤ ∫xf/∫f','real,ineq','Chebyshev 积分不等式',2),
(2017,'ANA','Individual','2','闭集 E 的等距集 E_r={d(x,E)=r} 可测且测度为零','real','覆盖 / 测度论',2),
(2017,'ANA','Individual','3','w=∫_0^w(1−x^n)^{−2/n}dx 是圆到正 n 边形的共形映射及其 Laplace 边值问题','cplx,pde','Schwarz–Christoffel 公式',4),
(2017,'ANA','Individual','4','热方程初边值问题解的唯一性，并证明一致有界条件 (∗) 是必要的','pde','极大值原理 / 反例构造',3),
(2017,'ANA','Individual','5','可压缩流体方程组：能量泛函单调不增；v 关于 t 的上下界（含 v_0^{-γ} 的显式估计）','pde','能量方法 / 熵估计',5),
(2018,'ANA','Individual','1','图与锥不相交 ⟹ Lipschitz；Lipschitz 映射可延拓到全空间','real','几何测度 / McShane 延拓',3),
(2018,'ANA','Individual','2','不用 Riemann 映射定理证明单连通真域上存在单叶映到单位圆盘的函数','cplx','正规族 / Montel 定理',4),
(2018,'ANA','Individual','3','n 次多项式满足 |P(0)| ≤ C∫_{−1}^{1}|P(x)|dx','approx','多项式不等式 / Markov 型',3),
(2018,'ANA','Individual','4','Δu+√u=0, u>0 in Ω, u|∂Ω=0 的解唯一','pde','极大值原理 / 单调性',4),
(2018,'ANA','Individual','5','算子 u(x)_j=Σ_k x_k/(j+k) 在 ℓ² 上的范数 ‖u‖=π','func,harm','Hilbert 矩阵 / 积分表示',4),
(2019,'ANA','Individual','1','投影 E,F 满足 ‖E−F‖≤1/2 ⟹ 存在酉 U 使 UEU*=F','func','算子扰动 / 谱投影',3),
(2019,'ANA','Individual','2','∀f∈L¹, fg∈L¹ ⟹ g∈L^∞；并给出 ‖g‖_∞ 的对偶刻画','real','对偶 / 一致有界原理',3),
(2019,'ANA','Individual','3','穿孔圆盘上调和函数的圆周平均等于 α log r + β','potential','调和函数 / 平均值性质',3),
(2019,'ANA','Individual','4','(0,1)×(0,∞) 上 Δu=0, u>0, u|∂D=0 的全部解','pde','调和函数 / 极大值原理',4),
(2019,'ANA','Individual','5','Legendre 多项式：正交性、实单根、Gauss 求积节点与 L² 最佳逼近','approx','正交多项式 / Gauss–Legendre 求积',3),
(2020,'ANA','Individual','1','|f′|≥β ⟹ m{|f|≤ε} ≤ 2ε/β；q 阶导数的相应估计','real','Lebesgue 测度 / 覆盖论证',3),
(2020,'ANA','Individual','2','截断指数 E_p(z) 满足 |1−E_p(z)| ≤ |z|^{p+1} (|z|≤1)','cplx','幂级数余项估计',2),
(2020,'ANA','Individual','3','用初等积分求解 x dy/dx = √(x⁶−y²) + 3y','ode','Riccati 型 / 变量替换',3),
(2020,'ANA','Individual','4','非降函数 f′ 可积且 ∫f′ ≤ f(1)−f(0)；级数可逐项求导 a.e.','real','单调函数 / Vitali 覆盖',3),
(2020,'ANA','Individual','5','f(0)=0, |f(e^{iθ})|≥3 ⟹ 1−f 在单位盘内零点的乘积模 < 1/2','cplx','Jensen 公式 / 零点估计',4),
(2020,'ANA','Individual','6','Σa_ij u_ij − u ≥ 0 且 u ≤ 2020+|x|^{2020} ⟹ u ≤ 0','pde','极大值原理 / 一致椭圆',3),
(2021,'ANA','Individual','1','l²(Z)→l⁴(Z) 嵌入是否连续、是否紧、是否模平移紧','func','紧算子 / 平移不变性',4),
(2021,'ANA','Individual','2','凸开集的投影长度（或投影集）相同能否推出两凸集相同','real,geom','凸几何 / Radon 变换',3),
(2021,'ANA','Individual','3','∇(ρ^{4/3})+ρ∇φ=0（φ 为 Newton 势）时积分 ∫(3ρ^{4/3}+ρφ/2) 的值','pde','Thomas–Fermi 方程 / 变分恒等式',5),
(2021,'ANA','Individual','4*','确定单位圆盘的全纯自同构群 Aut(D)（选做）','cplx','Schwarz 引理 / Möbius 变换',2),
(2021,'ANA','Individual','5*','内积空间中 x_k ⇀ x ⟹ 存在子列其 Cesàro 平均强收敛到 x（选做）','func','Banach–Saks 性质',3),
(2022,'ANA','Individual','1','f_k ⇀ f in L^q 且 f_k→f a.e. ⟹ lim(‖f_k‖−‖f_k−f‖)=‖f‖','real','Brezis–Lieb 引理',3),
(2022,'ANA','Individual','2','按 f′(z0)=sup_{g∈F}|g′(z0)| 的策略详细解释 Riemann 映射定理的证明','cplx','正规族 / 极值函数',4),
(2022,'ANA','Individual','3','u_t=u_xx/u_x² 且 u_x>0：找一个变换把该非线性热方程化为线性 PDE','pde','Hopf–Cole 型变换 / 拟线性化',3),
(2022,'ANA','Individual','4','变系数线性波动方程的能量估计（含 Σ‖∂g_{αβ}‖_{L²} 的指数因子）','pde,wave','能量方法 / Gronwall 不等式',4),
(2023,'ANA','Individual','1','Schwartz 函数的不确定性原理 ∫x²|ψ|²·∫|ψ′|² ≥ 1/4，等号 ⟺ 高斯','harm','Fourier 变换 / 分部积分 / Cauchy–Schwarz',3),
(2023,'ANA','Individual','2','f 在闭盘邻域除单位圆上极点 z0 外全纯 ⟹ lim a_n/a_{n+1}=z0','cplx','奇点展开 / 系数比',3),
(2023,'ANA','Individual','3','平面系统 ẋ=xy+x³, ẏ=−y−2x² 在 (0,0) 的稳定性','ode,dyn','线性化 / Lyapunov 函数',3),
(2023,'ANA','Individual','4','{y>x²} 上有界调和函数且边界值为 0 ⟹ 恒为 0','pde','极大值原理 / 无界域 Liouville',3),
(2024,'ANA','Individual','1','保向光滑映射的 Beltrami 系数 μ=|φ_z̄|/|φ_z|<1；圆映为椭圆且 μ 为轴比','cplx','拟共形映射 / 椭圆模',3),
(2024,'ANA','Individual','2','热方程 Cauchy 问题在 t=1/1000 是否有零点、能否在 t=1 复现方波；波动方程 t=1000 时是否有零点','pde','热核 / 有限传播速度',4),
(2024,'ANA','Individual','3','Δu=0 于穿孔球 B−{0}, u>0, u|∂B=v|∂B, Δv=0 于 B ⟹ u≥v','pde','调和函数 / 可去奇点 / 比较原理',4),
(2024,'ANA','Individual','4','lim_{λ→∞}∫e^{iλx²}φ(x)dx=0 且 |∫e^{iλx²}φ| ≤ Cλ^{−α}','harm','驻相法 / 振荡积分',3),
(2025,'ANA','Individual','1','{nα} 在 [a,b] 中的频率收敛到 b−a（Weyl 等分布）','ergodic','等分布 / 三角和估计',3),
(2025,'ANA','Individual','2','第一象限上有界全纯函数在边界模约束下满足 |f(x+iy)| ≤ 2^{(2/π)arctan(1/(2xy))}','cplx','Phragmén–Lindelöf / 调和测度',5),
(2025,'ANA','Individual','3','V 是 L²([0,1]) 的闭子空间且 V⊂C([0,1]) ⟹ dim V < ∞','func','紧嵌入 / 一致有界',3),
(2025,'ANA','Individual','4','Δ²u=0 且 u≥0 于 R^n ⟹ u=Σa_i(x_i−b_i)²+a_0','pde','双调和 Liouville 定理',4),
# ---------------- ANA Overall ----------------
(2015,'ANA','Overall','1','Cauchy 函数方程：连续 ⟹ 线性；Borel 可测 ⟹ 连续','real','Cauchy 方程 / 可测性',2),
(2015,'ANA','Overall','2','概率测度 μ̂(ξ0)=1 ⟹ supp μ 含于 Z 的平移伸缩','harm','Fourier 变换 / 测度刚性',4),
(2016,'ANA','Overall','1','正定对称 A 满足 tr A≤N+ε, det A≥1−ε ⟹ ‖A−I‖_HS ≤ C_N√ε','linear','谱分解 / 特征值扰动',3),
(2016,'ANA','Overall','2','T_n(e_m)=e_{nm}：{T_n,T_n*} 与 {T_m,T_m*} 交换 ⟺ (n,m)=1；与所有 T_n 交换的算子为 cI','func','算子代数 / 交换子',4),
(2017,'ANA','Overall','1','单位盘上全纯函数的 Schwarz–Pick 型双边估计','cplx','Schwarz–Pick 不等式',3),
(2017,'ANA','Overall','2','凸函数满足 |f(x)|≤C(1+|x|)：f(x)/|x| 的极限、上界与下界','real','凸分析 / 渐近斜率',2),
(2017,'ANA','Overall','3','Δu=x/(x²+y²) 于单位盘、u|∂=0：是否有弱解及最优连续性','pde','弱解 / 椭圆正则性',4),
(2018,'ANA','Overall','1','f 在单位圆盘邻域解析且在 ∂U 上取实值 ⟹ f 为常数','cplx','Schwarz 反射 / 唯一性',2),
(2018,'ANA','Overall','2','求 −u″=f 在周期边值条件 u(0)=u(1), u′(0)=u′(1), ∫u=∫f=0 下的 Green 函数','ode','Green 函数 / 周期边值',3),
(2018,'ANA','Overall','3','Hardy 不等式 ∫|v|²/|x|² ≤ C∫(|v_r|²+R^{−2}v²)','harm,ineq','Hardy 不等式 / 径向导数',4),
(2019,'ANA','Overall','1','f(x,y) 限制到每条直线上连续是否推出 f 连续','real','多元连续性 / 反例构造',2),
(2019,'ANA','Overall','2','证明 π²/sin²(πz) = Σ_{n∈Z} 1/(z−n)²','cplx','部分分式 / Mittag-Leffler',3),
(2019,'ANA','Overall','3','Δu=cos(xy)/√(x²+y²) 于单位盘、u|∂=0：解的意义与经典解成立范围','pde','弱解 / 奇性',3),
(2020,'ANA','Overall','1','用十进制构造实数：有界递增十进制序列有十进制极限','real','实数构造 / 完备性',3),
(2020,'ANA','Overall','2','Σx_ix_j f_{ij}=0 且 ∇f(0)=0 ⟹ f 常数；旋转不变 ⟹ 球面上常数','pde','极值原理 / 齐次函数',3),
(2021,'ANA','Overall','1','解释 L^∞(R) 的对偶空间不是 L^1(R)','func','对偶 / 测度表示',2),
(2021,'ANA','Overall','2','G(t)=∫|φ(x)−t|dx 连续；在 t 可导 ⟺ λ({φ=t})=0','real','Lebesgue 积分 / 可导性',3),
(2021,'ANA','Overall','3','∫_{B}|v|²/|x|² ≤ C(∫|v_r|² + ∫_{∂B}|v|²)（迹不等式）','harm','Hardy / 迹定理',4),
(2021,'ANA','Overall','4','方程 dy/dx=x²+y² 的任何解生命期有限','ode','比较定理 / 爆破',2),
(2022,'ANA','Overall','1','非常数整函数的像是稠密的，且最多漏掉一个点','cplx','Picard 小定理 / 正规族',3),
(2022,'ANA','Overall','2','积分算子 T 的有界性（Schur 检验）、Hilbert–Schmidt 紧性、弱奇异核的紧性','func','Schur 检验 / Arzelà–Ascoli',4),
(2022,'ANA','Overall','3','3 维波动方程径向解：∂_r(rφ)(0,t)≡0 (t≥T0)；在 u=t−r 坐标下的非零极限','pde,wave','球平均法 / 降维',5),
(2023,'ANA','Overall','1','卷积算子 Tf=f∗φ 是否把 L³(R³) 有界映到 L²(R³)','harm','Young 不等式 / 齐次性检验',4),
(2023,'ANA','Overall','2','给定单位盘内离散点列，构造以该点列为零点集的全纯函数','cplx','Weierstrass 乘积 / Blaschke 因子',3),
(2024,'ANA','Overall','1','u 关于每个变量 1-周期 ⟹ ∫_{[0,1]²}det(D²u+A) = det A','pde','弱收敛 / 行列式的散度结构',4),
(2024,'ANA','Overall','2','σ(AB)=σ(BA)；A,B 不可逆时结论如何','func','谱理论 / 交换性',2),
(2025,'ANA','Overall','1','∫|f|max{1,log|f|} < ∞ ⟹ 极大函数 ∫Mf < ∞','harm','Hardy–Littlewood 极大函数 / 分布函数',3),
(2025,'ANA','Overall','2','环面上线性 Schrödinger 方程的 Strichartz 型估计 ∫∫|u|⁴ ≤ C(∫|f|²)²','harm,pde','Fourier 级数 / Plancherel / Strichartz',4),
# ---------------- ANA Team ----------------
(2015,'ANA','Team','1','f∈C_c^∞(R²) 且沿每条直线的积分为 0 ⟹ f≡0','harm','Radon 变换 / 卷积',3),
(2015,'ANA','Team','2','存在域 D 使 Aut(D) 可数无限；使 Aut(D)≅Z；Aut(D)≅R 是否可能','cplx','Riemann 面 / 自同构群',4),
(2015,'ANA','Team','3','∫ 1/|f| = +∞（f∈C¹）⟹ ẋ=f(x) 的解存在区间为 (−∞,∞)','ode','解的存在区间 / 比较',3),
(2016,'ANA','Team','1','多项式满足 M(R)/R^n ≤ M(r)/r^n，等号 ⟺ f(z)=cz^n','cplx','最大模原理',2),
(2016,'ANA','Team','2','b1=1,b2=2,b_{n+1}=b_n+b_{n−1}，判断 Σ1/b_n 是否收敛','real','Fibonacci 增长 / 比值判别',2),
(2016,'ANA','Team','3','Δu=0 于穿孔球 B1−{0}, u=0 于 ∂B1, u≥0 的全部解','pde,potential','可去奇点 / 调和函数',3),
(2016,'ANA','Team','4','C¹ 函数的临界值集测度为零','real','Sard 定理（一维）/ 覆盖',2),
(2016,'ANA','Team','5','迭代不等式 w(τr)≤γw(r)+σ(r) 的解估计（Morrey 型）','harm','迭代引理 / Campanato 技巧',4),
(2016,'ANA','Team','6','根在 (−1,1) 的首一实多项式经 Chebyshev 代换后根仍在 (−1,1)','approx,special','Chebyshev 多项式 / 交错',4),
(2017,'ANA','Team','1','球平均相等的两个测度：绝对连续时相等；一般不绝对连续时如何','real','测度论 / 微分定理',3),
(2017,'ANA','Team','2','f:Ω→Ω 解析，f(z0)=z0 且 f′(z0)=1 ⟹ f=id','cplx','Schwarz 引理',3),
(2017,'ANA','Team','3','第一象限上 Δu=0, u>0, 边界为 0 的全部解','pde','调和函数 / Poisson 核',3),
(2017,'ANA','Team','4','理想流体方程组：∫|v|² 守恒；无旋且有非零梯度 ⟹ ∂P/∂n<0','pde','能量恒等式 / 涡度 / 自由边界',5),
(2018,'ANA','Team','1','等周不等式与 Steiner 对称化：等周集是凸的；面积不变、周长不减；只有圆盘是等周集','geom','Steiner 对称化 / Brunn–Minkowski',4),
(2018,'ANA','Team','2','用 Hankel 围道积分表示 ζ(s) 并证明其亚纯延拓','cplx','围道积分 / 解析延拓',4),
(2018,'ANA','Team','3','轴对称热方程基本解的显式表达式（含函数 H(y)）','pde','热核 / 分离变量 / Bessel',5),
(2018,'ANA','Team','4','带近似法向场的 Korn 型不等式','pde','Korn 不等式 / 分部积分 / 边界修正',5),
(2019,'ANA','Team','1','R¹×[0,1] 上有界凸函数（可不光滑）不依赖 x','real','凸分析 / 单调性',3),
(2019,'ANA','Team','2','帐篷映射存在轨道在 [0,1] 中稠密的点','dyn','符号动力学 / 二进制展开',2),
(2019,'ANA','Team','3','Burgers 方程：一致有界、周期性、∂_x u ≤ 1/t、全变差一致有界、ε→0 的收敛','pde','极大值原理 / 守恒律 / BV 估计',5),
(2019,'ANA','Team','4','上半圆盘上 Δu=0, u>0, 边界为 0 的全部解','pde','调和函数 / 极大值原理',3),
(2023,'ANA','Team','1','两个椭圆曲线之间的全纯映射必为 f(z)=az+b','cplx','Liouville / 双周期性',4),
(2023,'ANA','Team','2','有界自伴算子谱非空；无界自伴算子谱是否非空','func','谱定理 / 近似点谱',3),
(2023,'ANA','Team','3','(−Δ+|x|²)g_n=f_n 且 f_n 在 L² 有界 ⟹ g_n 有界且有 L² 收敛子列','func,pde','谐振子 / 紧预解 / Rellich',4),
(2024,'ANA','Team','1','半空间波动方程的混合问题：M 为一阶传输算子，证 □(Mu)=0 并求 u','pde,wave','半空间反射 / 传输方程',5),
(2024,'ANA','Team','2','A≥B≥0 的两自伴算子，存在压缩算子 T 使 B=T*AT','func','Löwner 定理 / 算子单调性',3),
(2024,'ANA','Team','3','上半平面 ∫_H y^{k−2}|f| < ∞ ⟹ y^k f 有界','cplx','Bergman 空间 / 次调和函数',4),
(2025,'ANA','Team','1','用网格地址系统给出 [0,1]² 上函数的组合逼近，误差 ≤ 6.01/7‖f‖（宣称是 AI 的数学基础）','approx','分片线性逼近 / 覆盖论证',4),
(2025,'ANA','Team','2','Banach 空间上 L_t=(1−t)L_0+tL_1 满足 ‖x‖≤C‖L_tx‖ ⟹ L_0,L_1 满射性等价','func','开映射定理 / 同伦方法',3),
(2025,'ANA','Team','3','Δu=f, u=g on Γ, ∂u/∂n=0 on Γ 的混合边值问题至多一解','pde','能量方法 / 唯一性',3),
]
