# -*- coding: utf-8 -*-
"""追加 finals_alg_ana.md 的 §3-§5。BT 代表反引号。"""
import sys, os, re, json, collections
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from finals_alg_ana_problems import P
from finals_alg_ana_extras import E
ROOT = r'E:\deepseek_exclusive\math'
OUT = os.path.join(ROOT, '.tmp', 'burn2026', 'reports', 'finals_alg_ana.md')

def nrm(rec, src):
    y, s, k, no, desc, tags, meth, d = rec[:8]
    try: d = int(d)
    except Exception: d = None
    return dict(y=y, s=s, k=k, no=no, desc=desc, tags=[t.strip() for t in tags.split(',')], meth=meth, d=d, src=src)
A = [nrm(r, 'pdf') for r in P]; B = [nrm(r, 'doc') for r in E]; ALL = A + B
L = []
def o(s=''): L.append(s)

o()
o('---')
o()
o('## 3. 考点频次表')
o()
o('### 3.1 子领域标签定义与频次（244 题；主集=PDF，恢复=.doc/.docx）')
o()
o('ALG 侧：BTlinearBT 线性代数/矩阵；BTcommBT 交换代数与环；BTantBT 代数数论；BTrepBT 表示论；BTgroupBT 群论；')
o('BTfieldBT 域论；BTgaloisBT Galois 理论；BTagBT 代数几何；BTpolyBT 多项式；BTquadBT 二次型/平方和；')
o('BThomolBT 同调代数与模；BTsylowBT Sylow 与有限群结构；BTpadicBT p 进与局部域；BTcatBT 范畴论；BTcombBT 组合；BTvaluaBT 赋值论。')
o()
o('ANA 侧：BTpdeBT 偏微分方程；BTrealBT 实分析/测度；BTcplxBT 复分析；BTharmBT 调和分析与 Fourier；')
o('BTfuncBT 泛函分析与算子；BTodeBT 常微分方程；BTineqBT 不等式；BTpotentialBT 位势/调和函数；')
o('BTapproxBT 逼近与正交多项式；BTdynBT 动力系统；BTgeomBT 几何测度；BTwaveBT 波动/色散；')
o('BTergodicBT 遍历论；BTspecialBT 特殊函数。')
o()
o('| 考点 | 题次 | 主集 | 恢复 | ALG | ANA | 出现年份(20xx) |')
o('|---|---|---|---|---|---|---|')
tc = collections.Counter(); ty = collections.defaultdict(set); ts = collections.defaultdict(collections.Counter)
tA = collections.Counter(); tB = collections.Counter()
for x in ALL:
    for t in x['tags']:
        if t == '—': continue
        tc[t] += 1; ty[t].add(x['y']); ts[t][x['s']] += 1
        (tA if x['src'] == 'pdf' else tB)[t] += 1
for t, c in tc.most_common():
    o('| BT%sBT | %d | %d | %d | %d | %d | %s |' % (t, c, tA[t], tB[t], ts[t]['ALG'], ts[t]['ANA'],
        ','.join(str(v)[2:] for v in sorted(ty[t]))))
o()
o('### 3.2 考点 × 年份 题次矩阵（前 18 个考点）')
o()
years = sorted(set(x['y'] for x in ALL))
o('| 考点 | ' + ' | '.join(str(y)[2:] for y in years) + ' | 合计 |')
o('|---|' + '---|' * (len(years) + 1))
for t, c in tc.most_common(18):
    row = [str(sum(1 for x in ALL if x['y'] == y and t in x['tags'])) if sum(1 for x in ALL if x['y'] == y and t in x['tags']) else '.' for y in years]
    o('| %s | %s | %d |' % (t, ' | '.join(row), c))
o()
o('### 3.3 方法/定理关键词频次（按题计）')
o()
mc = collections.Counter()
for x in ALL:
    for p in re.split(r'[/、]', x['meth']):
        p = p.strip()
        if p and p != '—': mc[p] += 1
o('| 方法/定理 | 题次 |')
o('|---|---|')
for t, c in mc.most_common(30):
    o('| %s | %d |' % (t, c))
o()
o('> §3 全部数字由 BTfinals_final_stats.pyBT 从逐题标注库 BTfinals_alg_ana_problems.pyBT + BTfinals_alg_ana_extras.pyBT 汇总，')
o('> 标签是**人工逐题标注后再机器汇总**，不是关键词匹配噪声。卷面动词的机器统计见 BTfinals_alg_ana_stats.pyBT 与 §4。')
o()

o()
o('---')
o()
o('## 4. 总决赛 vs 初赛（笔试）的差异')
o()
o('对比基准取自既有笔试报告：BT.tmp/burn2026/reports/stats_overview.mdBT（136 PDF / 120 卷 / 759 题）与')
o('BT.tmp/burn2026/reports/problem_metrics.mdBT（679 道可度量题）。以下 8 条差异均有计数支撑。')
o()
o('### D1. 卷别体系多一层：笔试只有 Individual/Team，总决赛多出 Overall（All-round）')
o('- 笔试：stats_overview.md §3 的 120 卷明细中卷别只有 BTindividualBT / BTteamBT 两类，**没有 Overall 类**。')
o('- 总决赛：73 卷里 **24 卷是 Overall**（占 33% 的卷数），共 **54 题**（占 244 题的 22%）。')
o('- Overall 卷题量最少（**2.25 题/卷**），卷面多写 BTAll-roundBT / BTAll-aroundBT / BTOverall individual roundBT，')
o('  是总决赛特有的「口试总轮」。**只看笔试语料会系统性漏掉这 22% 的真题。**')
o()
o('### D2. 单卷题量只有笔试的一半左右')
o('- 笔试 759 题 / 120 卷 = **6.32 题/卷**；总决赛 244 题 / 73 卷 = **3.34 题/卷**。')
o('- 分卷别：Individual 4.14、Team 3.52、Overall 2.25 题/卷。')
o('- 佐证：笔试报告多卷标注「解析题数 6」，而总决赛 14 年里最大的卷面题号是 6（2020 ALG Individual）。')
o()
o('### D3. 命题动词更偏证明：计算类几乎消失')
o('- 机器统计（BTfinals_alg_ana_stats.pyBT，对本范围 67 卷全文计数）：')
o('  - ALG：prove 63 / show 42 / find 8 / compute+calculate 4 / determine 10 / solve 1 / classify 8 / describe 7')
o('  - ANA：prove 61 / show 41 / find 9 / compute+calculate 2 / determine 2 / solve 16 / estimate 3')
o('  - ALG 中 prove+show 占全部动词的 88%，纯计算类仅 4 次。')
o('- 笔试对照（problem_metrics.md §4）：compute 64 题、calculate 19 题、derive 27 题、solve 25 题、evaluate 5 题，')
o('  计算/推导类动词覆盖 110 题以上（约 16% 的题），显著高于总决赛。')
o()
o('### D4. 题目长度：分析卷变长、代数卷变短')
o('- 剔除附官方解答的 2021 代数两卷后：总决赛 **ALG 61.0 词/题**（92 题）、**ANA 56.5 词/题**（110 题）。')
o('- 笔试：**ALG 84 词/题**、**ANA 49 词/题**（problem_metrics.md §2）。')
o('- 即 ANA 由 49 升到 56.5（+15%），ALG 由 84 降到 61（−27%）。')
o('- 解释：总决赛代数题常是「短题干 + 长推导」（2025 ALG Individual Q2 只有一行），')
o('  分析题则必须写清方程、区域、边界条件与待证估计，题面自然更长。')
o()
o('### D5. 考点重心不同：总决赛把权重压到核心硬分析 + 线性代数 + 交换代数/数论')
o('- 总决赛 ANA 前四：**pde 33、real 30、cplx 28、harm 16**（func 15）。')
o('  笔试（problem_metrics.md §3）：复分析 36、PDE 27、实分析 26、泛函 15、调和/位势 18。')
o('  即总决赛**明显抬高 PDE 与调和分析权重**，并新增笔试几乎不考的波动/色散（3 题）与遍历论（1 题）。')
o('- 总决赛 ALG 前四：**linear 32、comm 18、ant 18、rep 16**（group 15、field 13、galois 11）。')
o('- 笔试几乎不涉及的高端考点在总决赛反复出现：p 进/局部域 **3 题**（2021 范数群、2022 平方和、2025 Q_3 不可约性）、')
o('  同余数与椭圆曲线（2019 ALG Team #4）、赋值完备化（2019 ALG Team #3）、范畴中心（2016 ALG Team #2）、')
o('  Weyl/Clifford 代数单模（2016 ALG Team #3、2024 ALG Individual #3）、Mason–Stothers（2024 ALG Team #2）。')
o()
o('### D6. 难度整体上移')
o('- 总决赛自评难度：均值 **3.32**，≥4 占 **38%**（92/240），=5 有 **18 题**。')
o('- 笔试启发式难度代理 ALG 2.64 / ANA 1.72（problem_metrics.md §2；口径为长度+小问数+符号密度，不能直接相减）。')
o('- 更可比的口径：笔试 ANA 平均小问 0.51，而总决赛 ANA 大量题带 (1)(2)(3) 多步结构')
o('  （2023 ANA Individual #1 的 (i)(ii)(iii)、2024 ANA Individual #2 的 (i)(a)(b)(ii)、2019 ANA Individual #5 的四小问），')
o('  同一道题要求的推导链条更长。')
o()
o('### D7. 卷面形式：总决赛是「口试」，笔试是「笔试」')
o('- 出现 **Oral / ORAL** 的卷共 6 卷：2012 ALG Individual（ALGEBRA ORAL）、2013 ALG Individual（Individual Oral Test）、')
o('  2013 ALG Team（Team Oral Test）、2014 ALG Individual（2014 ORAL EXAM）、2021 ANA Individual / 2021 ANA Overall（12th Oral Exam）。')
o('- 另有 BTAll-round / Overall / All-aroundBT 共 11 卷、BTFinal ContestBT 3 卷（2023）。')
o('- 笔试语料没有这类口试标记，且 2020–2022 出现「试卷 + 解答」成对文件。')
o()
o('### D8. 总决赛有「选做」机制，笔试没有')
o('- 总决赛 **8 卷**允许选做（BTfinals_forms.pyBT 关键词扫描 + 逐卷人工核对）：')
o('  - 2023 ANA Individual：solve three out of the following four problems')
o('  - 2023 ANA Overall：solve one of the following two problems')
o('  - 2023 ANA Team：solve two from the following three problems')
o('  - 2023 ALG Individual：Choose (1) or (2), but not both')
o('  - 2025 ANA Individual：solve at least three out of the following four')
o('  - 2025 ANA Overall：solve one out of the following two')
o('  - 2025 ANA Team：solve at least two out of the following three')
o('  - 2021 ANA Individual 第 4、5 题标注 optional（星号）')
o('- 选做机制**全部集中在 2021 年之后的 ANA**（2023 年 4 卷 + 2025 年 3 卷 + 2021 年 1 卷，共 8 卷），是总决赛近年最显著的卷面变化。')
o()

o()
o('---')
o()
o('## 5. Individual 卷 vs Team 卷差异')
o()
o('### 5.1 总体量化（含恢复集）')
o()
o('| 指标 | Individual | Team | Overall |')
o('|---|---|---|---|')
rows = []
for g in ('Individual', 'Team', 'Overall'):
    it = [x for x in ALL if x['k'] == g]
    dd = [x['d'] for x in it if x['d']]
    n = len(set((x['y'], x['s']) for x in it))
    rows.append((n, len(it), len(it) / n, sum(dd) / len(dd), 100 * sum(1 for d in dd if d >= 4) / len(dd)))
o('| 卷数 | %d | %d | %d |' % tuple(r[0] for r in rows))
o('| 题数 | %d | %d | %d |' % tuple(r[1] for r in rows))
o('| 题/卷 | %.2f | %.2f | %.2f |' % tuple(r[2] for r in rows))
o('| 难度均值(自评) | %.2f | %.2f | %.2f |' % tuple(r[3] for r in rows))
o('| 难度 ≥4 占比 | %.0f%% | %.0f%% | %.0f%% |' % tuple(r[4] for r in rows))
o()
o('### 5.2 分科目难度分布')
o()
o('| 科目 | 卷别 | 题数 | 难度均值 | 1 | 2 | 3 | 4 | 5 |')
o('|---|---|---|---|---|---|---|---|---|')
for s in ('ALG', 'ANA'):
    for g in ('Individual', 'Team', 'Overall'):
        it = [x for x in ALL if x['s'] == s and x['k'] == g]
        dd = [x['d'] for x in it if x['d']]
        o('| %s | %s | %d | %.2f | %s |' % (s, g, len(it), sum(dd) / len(dd),
            ' | '.join(str(sum(1 for d in dd if d == i)) for i in range(1, 6))))
o()
o('### 5.3 六条差异结论')
o()
o('**T1. 题量：Individual > Team > Overall（4.14 : 3.52 : 2.25 题/卷）。**')
o('Individual 卷 2018–2020 稳定 5–6 题（2018/2019 ALG 各 5 题、2020 ALG 6 题）；Team 卷 2–6 题；')
o('Overall 卷 1–4 题，且常写「solve one out of the following two」。')
o()
o('**T2. 难度：Team 卷最难。** 全部题合计：Team 3.56 > Overall 3.30 > Individual 3.18；')
o('难度 ≥4 的比例 Team **50%**、Individual 30%、Overall 38%。分科目看 **ANA Team 最高（3.64）**，')
o('18 道难度 =5 的题里 9 道出自 Team 卷（2013 ANA Team #3/#4、2017 ANA Team #4、2018 ANA Team #3/#4、')
o('2019 ANA Team #3、2024 ANA Team #1、2014 ANA Team #5、2013 ANA Overall #2）。')
o()
o('**T3. 题面长度：Team 卷最长。** ANA Team 平均 **71.5 词/题** vs ANA Individual 50.6 / Overall 51.6；')
o('ALG Team 64.7 vs ALG Individual 50.2。Team 题通常给出完整方程组、区域与多小问。')
o()
o('**T4. 结构：Team 卷偏爱「带引导的分步证明」。**')
o('2013 ALG Team #1 把「tr(Aⁿ)∈F ∀n≥2 ⟹ tr(A)∈F」拆成 a)–d) 四步并附 Hint；')
o('2018 ANA Team #1 把等周不等式拆成「凸性 → Steiner 对称化 → 只有圆盘」三步；')
o('2019 ALG Team #4 把同余数问题拆成 (a) 判别式、(b) 无穷多 n≡r (mod 8)。')
o('Individual 卷则多为单问直给（2016 ALG Individual #3、2019 ALG Individual #5 各只有一句话）。')
o()
o('**T5. 考点分化：Team 承担体系性/工具性考点，Individual 承担基础必修考点。**')
o('- 只在 Team 出现的（代数）：范畴的中心（2016 #2）、Nakayama（2018 #3）、Chevalley–Warning（2018 #1）、')
o('  Noether 有限性（2018 #2）、Schanuel 引理（2019 #5）、模表示 Clifford 定理（2014 #4）、')
o('  赋值完备化（2019 #3）、同余数（2019 #4）、Mason–Stothers（2024 #2）、射有限群 Ẑ（2024 #3）。')
o('- 只在 Team 出现的（分析）：Steiner 对称化/等周（2018 #1）、ζ 的围道积分（2018 #2）、')
o('  Korn 不等式（2018 #4）、Burgers 全变差（2019 #3）、半空间波动方程（2024 #1）、')
o('  Gelfand 极大理想空间（2014 #5）、迭代引理（2014 #4）、爆破（2013 #3）。')
o('- 只在 Individual 出现的：Gauss 和次数（2020 #3）、det(A)²∈Z（2020 #4）、Q_p(ζ_{pⁿ}) 范数群（2021 #1）、')
o('  ∧²V（2021 #2）、Molien 公式（2023 #3）；分析侧：不确定性原理（2023 #1）、Legendre 求积（2019 #5）、')
o('  Phragmén–Lindelöf 型边界估计（2025 #2）、等分布（2025 #1）。')
o()
o('**T6. 2020–2022 三年 Team 卷整体缺席。** ALG Team 缺 2014、2020、2021、2022；ANA Team 缺 2012–2014、2020、2021、2022。')
o('2020–2022 连续三年两个科目**都没有 Team 卷**；核对 F 盘目录后确认这不是抽取失败（目录里确实没有对应文件），属赛制/语料共同缺口。')
o()

open(OUT, 'a', encoding='utf-8').write('\n'.join(L).replace('BT', chr(96)) + '\n')
print('appended lines:', len(L))
